name: Cypress Tests And Reports
on: [push]
jobs:
  install:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.7.0
        
      - name: Cypress run
        uses: cypress-io/github-action@v5.6.1
        with:
            command: npm run test
      
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
           name:  cypress-execution-report
           path: D:/a/Repo2/Repo2/cypress/reports/html
           retention-days: 3
        
        
