name: Cypress Tests
on: [Push]
Jobs:
   cypress-run:
      runs-on: ubuntu-latest
     steps:
   - name: Checkout
     uses: actions/checkout@v2.7.0
   
   - name: Cypress.io
   uses: cypress-io/github-action@v5.6.1
 
